application: PROJECT_ID
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: MySQLdb
  version: "latest"

env_variables:
    DATABASE: >-
      mysql://SQL_PROD_USER:SQL_PROD_PASS@SQL_IP_ADDRESS:3306/SQL_INSTANCE_ID?unix_socket=/cloudsql/SQL_INSTANCE_CONNECTION_NAME

